import { LanguageType } from './types';

export const extensionMap: { [key: string]: LanguageType } = {
  '(.*).png': LanguageType.Image,
  '(.*).jpg': LanguageType.Image,
  '(.*).jpeg': LanguageType.Image,
  '(.*).svg': LanguageType.Image,
  '(.*)Dockerfile': LanguageType.Dockerfile,
  '(.*).jade': LanguageType.Jade,
  '(.*).java': LanguageType.Java,
  '(.*).js': LanguageType.Javascript,
  '(.*).jsx': LanguageType.Javascript,
  '(.*).json': LanguageType.JSON,
  '(.*).md': LanguageType.Markdown,
  '(.*)pom.xml': LanguageType.Maven,
  '(.*).patch': LanguageType.Patch,
  '(.*).py': LanguageType.Python,
  '(.*).rb': LanguageType.Ruby,
  '(.*).sass': LanguageType.Sass,
  '(.*).sh': LanguageType.Shell,
  '(.*).ts': LanguageType.Typescript,
  '(.*).tsx': LanguageType.Typescript,
  '(.*).xml': LanguageType.XML,
  '(.*).yaml': LanguageType.Yaml,
  '(.*)yarn.lock': LanguageType.Yarn,
};
